name: macOS
on:
  push:
    branches:
    - master
    
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/pkgbuild.yml
      - pkgbuild/**
jobs:
  pkgbuild:
    strategy:
      matrix:
        architecture: [x64, aarch64]
    name: pkgbuild
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Install dependencies
      run: brew install --cask packages

    - name: Setup environment variables
      uses: allenevans/set-env@0f3306034af0ea21dd28983b6e7c1614ee317739 # v3.0.0
      with:
        MAJOR_VERSION: 21
        FULL_VERSION: 21.0.1
        TAG: jdk-21.0.1+12
        SUB_TAG: 21.0.1
        JVM: hotspot

    - name: Download prebuilt binaries
      run: |
        mkdir -p workspace/target/
        cd workspace/target/
        wget -q "https://github.com/adoptium/temurin${{ env.MAJOR_VERSION }}-binaries/releases/download/${{ env.TAG }}/OpenJDK${{ env.MAJOR_VERSION }}U-jdk_${{ matrix.architecture }}_mac_${{ env.JVM }}_${{ env.SUB_TAG }}.tar.gz"

    - name: Create Package
      run: |
        export WORKSPACE=$PWD
        bash pkgbuild/create-installer-mac.sh

    - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: macOS_${{ matrix.architecture }}
        path: workspace/target/*.pkg
